StockEye/StockEye/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.fields import EmailField
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import WatchList

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'placeholder': 'Username'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'placeholder':'Password'}))

class CreateWatchListForm(forms.ModelForm):
    class Meta:
        model = WatchList
        fields = ['watchList_name']
        exclude = ['user', 'stockResults', 'watchList_id']

class EditWatchListForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditWatchListForm, self).__init__(*args, **kwargs)
        self.initial['stockResults'] = [s.pk for s in self.instance.stockResults.all()]
        self.initial['watchList_id'] = [self.instance.watchList_id]

    class Meta:
        model = WatchList
        fields = ['stockResults']
        exclude = ['watchList_name', 'user', 'watchList_id']

class UserChangeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(),required=False)
    email = forms.EmailField(widget=forms.EmailInput(), required=False, help_text="Hehee")
    class Meta:
        model = User
        fields = ['email']

StockEye/StockEye/app/templates/app/about.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<body>
<div class="jumbotron text-center">
        <h1>StockEye</h1>
        <p>Slogan</p>
    </div>

    <!-- Container (About Section) -->
    <div id="about" class="container-fluid">
        <div class="row">
            <div class="col-sm-8">
                <h2>About StockEye / Product Description</h2>
                <strong>

                    StockEye provides a streamlined web-based platform for investors and market enthusiasts to view the prospective performance of popular stocks based on Twitter sentiment analysis.

                </strong>
            </div>
            <div class="col-sm-4">
                <p><img src="{% static 'Images/laptop.png'%}" class="img-responsive center-block" width="1000" alt="Home"></p>
            </div>
        </div>
    </div>

    <div id="info" class="container-fluid bg-grey">
        <div class="row">
            <div class="col-sm-4">
                <img src="{% static 'Images/graph.jpg'%}" class="img-responsive center-block" alt="Graph" width="500">
            </div>
            <div class="col-sm-8">
                <h2>Product Functions</h2>
                <p>
                    <strong>StockEye must be fully documented and implemented by April 12th, and so time is a chief constraint. Machine learning is a key component of sentiment analysis, and the development team, as a whole, is largely unacquainted with its mechanism and details. Thus, it is expected that more time than ideal will be allocated to gathering and learning the prerequisites of machine learning demanded by the application. This is the primary obstruction in our objective to have a fully-functional implementation by the deadline. Furthermore, due to the COVID-19 pandemic, the team will be unable to coordinate in-person meetings, which could result in a reduction in productivity and clarity of communication. The project will have no expenses, due to the usage of free services during production of the application (django, python, etc). As such, the budget for this project is 0 dollars.</strong> 
                </p>
            </div>
        </div>
    </div>
    
    <div id="assumptions" class="container-fluid bg-grey">
        <div class="row">
            <!--<h2>Info</h2>-->

            <div class="col-sm-4">
                <img src="{% static 'Images/interfacePic.jpeg'%}" class="img-responsive center-block" alt="Graph" width="500">
            </div>
            <div class="col-sm-8">
                <h2>Assumptions and Dependencies</h2>
                <strong>
                    Users will be required to have access to the internet in order to access StockEye. Due to StockEye being entirely web-based, the user operating system is irrelevant.
                </strong>
            </div>
        </div>
    </div>

     <br><br><br><br><br>
     <p>&nbsp;</p>
   
</body>

<p>Use this area to provide additional information.</p>

{% endblock %}

StockEye/StockEye/app/templates/app/accountSettings.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<h3>User Profile</h3>
<h4>Change your Account Settings</h4>

<div class="navbar">
    <div class="col-md-12">
        <section id="UserChangeForm">
            <form action="." method="POST" class="form-horizontal">
                {% csrf_token %}
                <fieldset class ="form-group">
                        <div class="form-group">
                            <label for="id_email" class="col-md-5 control-label">Email</label>
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            <label for="id_password" class="col-md-5 control-label">New Password</label>
                            {{ form.password}}
                        </div>
          				<br>
                        <input type="hidden" name="next" value="/" />
                        <center><input type="Submit" value="Save Changes" class="register_button" /></center>
                
                <br>
                <br>
                <div style="text-align: center;" class="validation-summary-errors">
                    {% if form.errors %} 
                	Please enter a valid email address and/or password.
                    {% endif %}

                    {% if messages %}
                        {% for message in messages %}
                        <ul style="list-style-type:none; padding-left: 0px;">
                            <li>{{ message }}</li>
                        </ul>
                        {% endfor %}
                    {% endif %}
                </div>

            </form>
        </section>
    </div>
</div>
</div> 

{% endblock %}

StockEye/StockEye/app/templates/app/accountregistration.html
{% extends "app/layout.html" %}
{% block content %}

<h2>Account Registration</h2>
<div class="row">
    <div class="col-md-8">
        <section>
            <form>
                <div class="form-group">
                    <label for="username">Username:</label><input type="text" id="username" name="username"><br>
                    <div class="col-md-10">
                    {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="pword" class="col-md-2 control-label">Password:</label><input type="password" id="pword" name="pword"><br>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="c-pword" class="col-md-2 control-label">Confirm Password:</label><input type="password" id="pword" name="pword"><br>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-md-2 control-label">Email:</label><input type="email" id="email" name="email"><br>
                    div class="col-md-10">
                        {{ form.email}}
                    </div>
                </div>
                <input type="submit" value="Confirm Registration">

                

            </form>
        </section>
    </div>
</div>

{% endblock %}

StockEye/StockEye/app/templates/app/contact.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<body>

    <div id="team" class="container-fluid text-center">
        <h2>Meet The Team</h2>
        <p>&nbsp;</p>

        <div class="row">
            <div class="col-sm-4">
                <p class="text-center"><strong>Anshul Khatri</strong></p>
                <a href="#demo" data-toggle="collapse">    
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo" class="collapse">
                    <p>Email: khat3680@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Brayden Mckay</strong></p>
                <a href="#demo2" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo2" class="collapse">
                    <p>Email: mcka7400@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Campbell Leckie</strong></p>
                <a href="#demo3" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo3" class="collapse">
                    <p>Email: leck6240@mylaurier.ca</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <p class="text-center"><strong>Jeff Kolnick</strong></p>
                <a href="#demo4" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo4" class="collapse">
                    <p>Email: koln3930@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Leron Bergelson</strong></p>
                <a href="#demo5" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo5" class="collapse">
                    <p>Email: berg5310@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Nick Mills</strong></p>
                <a href="#demo6" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo6" class="collapse">
                    <p>Email: mill6100@mylaurier.ca</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <p class="text-center"><strong>Pericles Tsikrikis</strong></p>
                <a href="#demo7" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo7" class="collapse">
                    <p>Email: tsik9350@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Roy Ceyleon</strong></p>
                <a href="#demo8" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo8" class="collapse">
                    <p>Email: ceyl0550@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Ruth Schmidt</strong></p>
                <a href="#demo9" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo9" class="collapse">
                    <p>Email: schm4780@mylaurier.ca</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <p class="text-center"><strong>Tyler Price</strong></p>
                <a href="#demo10" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo10" class="collapse">
                    <p>Email: pric5180@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Yasmine Ali</strong></p>
                <a href="#demo11" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo11" class="collapse">
                    <p>Email: alix7910@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Mohsin Malik</strong></p>
                <a href="#demo12" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo12" class="collapse">
                    <p>Email: mali7370@mylaurier.ca</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <p class="text-center"><strong>Rafay Ahmed</strong></p>
                <a href="#demo13" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo13" class="collapse">
                    <p>Email: ahme0880@mylaurier.ca</p>
                </div>
            </div>
            <div class="col-sm-4">
                <p class="text-center"><strong>Michael Okenye</strong></p>
                <a href="#demo14" data-toggle="collapse">
                    <img src="{% static 'Images/ProfilePicture.jpg'%}" class="img-circle person" alt="Person" width="150" height="150">
                </a>
                <div id="demo14" class="collapse">
                    <p>Email: oken8340@mylaurier.ca</p>
                </div>
            </div>

        </div>
     </div>



</body>

{% endblock %}

StockEye/StockEye/app/templates/app/edit_watchlist.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<body>
    <div class="navbar">
        {% if watchlist_name %}
            <h1>Watchlist: {{ watchlist_name }}</h1>
        {% elif watchlist_id %}
            <h1>Watchlist: {{ watchlist_id }}</h1>
        {% else %}
            <h1>StockEye: Watchlist</h1>
        {% endif %}
            <h4>Edit your Watchlist</h4>
    </div>

    <!-- Container (Watchlist Section) -->
    <div class="content">
        {% if user.is_authenticated %}
            <p>Username: {{ user.username }}</p>
        {% else %}
            <p>Username: {{ user.username }} (Not a valid user)</p>
        {% endif %}
        <div>
            <button type="submit" class="btn-danger">Delete Selected Watchlists</button>
            <button type="submit" class="btn-danger">Select All</button>
        </div>
        <br></br>
        <table class="table table-bordered">
            <tr>
                {% if watchlist_name %}
                    <td colspan="5" style="text-align: center;">{{ watchlist_name }}</th>
                {% else %}
                    <td colspan="5" style="text-align: center;">Watchlist {{watchlist_id}}</th>
                {% endif %}
            </tr>
            <tr>
                <th>Symbol</th>
                <th># + Sentiments</th>
                <th># - Sentiments</th>
                <th>Value</th>
                <th>Select</th>
            </tr>
            {% for stock in stocks %}
            <tr>
                <td>{{ stock.symbol }}</td>
                <td>{{ stock.positiveSentimentCount }}</td>
                <td>{{ stock.negativeSentimentCount }}</td>
                <td>${{ stock.value }}</td>
                <td>
                    <input class ="form-check-input larger" name="delWatchListId" type="checkbox" value="{{watchlist.watchList_id}}">
                </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="form-group">
        <button class="btn-outline-info" type="submit">Save Changes</button>
    </div>

    <form id="editWatchListForm" action="{% url 'edit_watchlist' w_id=watchlist_id %}" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Stocks</legend>
            {{ form }}
        </fieldset>
        <div class="form-group">
             <button class="btn-outline-info" type="submit">Save Changes</button>
        </div>
        

    
   
</body>
{% endblock %}

StockEye/StockEye/app/templates/app/filterstocksview.html
{% extends "app/layout.html" %}
{% block content %}

<h2>Filter Stock View</h2>


<div class = "content">
     <table>
      <tr>
        {% if stocks.stock.id %}
        <p><a> href = "{% url 'stock' s_id = stocks.stock_id %}">{{stocks.tweet_id}}</a></p>
            <th>Name</th>
            <th>Price</th>
            <th>Sentiment</th>
        {% endif %}
      </tr>
      <tr>
          <td>{stocks.name}}</td>
          <td>{{stocks.price}}</td>
          <td>{{stocks.sentiment}}</td>
      </tr>
      </table>
    </div>   

{% endblock %}


           

StockEye/StockEye/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - StockEye</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    {% now "U" as u_time %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}?{{ u_time }}" />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">StockEye</a>
            </div>
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-left">
                        <li><a class="nav_button" href="{% url 'home' %}">Home</a></li>
                        <li><a class="nav_button" href="{% url 'trending' %}">Trending</a></li>   
                        <li><a class="nav_button" href="{% url 'watchlists' %}">My Watchlists</a></li>      
                    </ul>
                    <form id="logoutForm" action="/logout/" method="post" class="navbar-right">
                        {% csrf_token %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a class="register_button" href="{% url 'profile' %}">Profile Settings</a></li>         
                            <li><a class="login_button" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    </form>
                {% else %}
                    <ul class="nav navbar-nav navbar-left">
                        <li><a class="nav_button" href="{% url 'home' %}">Home</a></li>
                        <li><a class="nav_button" href="{% url 'trending' %}">Trending</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        
                        <li><a class="register_button" href="{% url 'register' %}">Register</a></li>
                        <li><a class="login_button" href="{% url 'login' %}">Log in</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
<br>
        <hr/>
        
        <footer>
            <p class="copyright">&copy; {{ year }} StockEye</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

StockEye/StockEye/app/templates/app/login.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<h3>Log in</h3>
<h4>Sign and start tracking stock sentiments</h4>

        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-5 control-label">Username</label>
                    <div class="col-md-6">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-5 control-label">Password</label>
                    <div class="col-md-6">
                        {{ form.password }}
                    </div>
                </div>

                <div align="center" class="form-group">
                    <input type="hidden" name="next" value="/" />
                    <input type="submit" value="Log in" class="register_button" />
                </div>
                <div style="text-align: center;">
                    {% if form.errors %}
                    <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                    {% endif %}
                </div>
            </form>
        </section>

<div class="border-top pt-3">
    <center>
        <small class="text-muted">
            Don't have an account? <a class="ml-2" href="../register/">Sign Up</a>
        </small>
    </center>
</div>

{% endblock %}


{% block scripts %}

{% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

StockEye/StockEye/app/templates/app/manage_watchlists.html
{% extends "app/layout.html" %}
{#{% load staticfiles %}#}
{% load static %}
{% block content %}

<body>

    <!-- Container (Watchlist Section) -->
    <div class="container overflow-hidden">

        <h2>Manage Watchlists</h2>
        <br><br>
        <form method="POST">
            {% csrf_token %}
            {% for watchlist in watchlists %}
            <div class="thumbnail watchlist-card">
                <div class="row justify-content-md-center">
                    <div class="col-md-4">
                        <div class="caption">
                            <h5 class="watchlist-caption"><a href="{% url 'edit_watchlist' w_id=watchlist.watchList_id %}" style="color: black;">{{ watchlist.watchList_name }}</a></h5>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <br>
                        <input class="form-check-input larger" name="delWatchListId" type="checkbox" value="{{watchlist.watchList_id}}">
                    </div>
                </div>
            </div>
            <br>

            {% endfor %}

            <div class="container overflow-hidden">
                <div class="btn-group" role="group" aria-label="Create or Delete Watchlist">
                    <div class="row gx-5">
                        <a href="{% url 'create_watchlist' %}" class="btn btn-dark rounded">Create Watchlist</a>
                        <button type="submit" class="btn btn-danger rounded">Delete Selected Watchlists</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
   
</body>
{% endblock %}

StockEye/StockEye/app/templates/app/registration.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<h3>Account Registration</h3>
<h4>Get started with StockEye</h4>

<div>
    <section id="registrationForm">
        <form action="." method="post" class="form-horizontal">
            {% csrf_token %}
            
            <hr />
            <div class="form-group">
                <label for="id_username" class="col-md-5 control-label">Username:</label>
                <div class="col-md-6">
                    {{ form.username }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_password" class="col-md-5 control-label">Password:</label>
                <div class="col-md-6">
                    {{ form.password1 }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_password2" class="col-md-5 control-label">Confirm Password:</label>
                <div class="col-md-6">
                    {{ form.password2 }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_email" class="col-md-5 control-label">Email:</label>
                <div class="col-md-6">
                    {{ form.email }}
                </div>
            </div>
            <div align="center" class="form-group">
                <button class="register_button" type="submit">Confirm Registration</button>
            </div>
            {% if form.errors %}
            <p class="validation-summary-errors">Please ensure valid registration information is provided.</p>
            {% endif %}
        </form>
    </section>
</div>

<div class="border-top pt-3">
    <center>
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="../login/">Sign In</a>
        </small>
    </center>
</div>

{% endblock %}


{% block scripts %}

{% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

StockEye/StockEye/app/templates/app/trending.html
{% extends "app/layout.html" %}
{#{% load staticfiles %}#}
{% load static %}
{% block content %}

<body>

<h3>Trending Stocks</h3>
<h4>Current trending stocks</h4>

</div>

       <div class="container">
        <div class= "trending_align"></div>
           <div class="row2">
            {% for stock in hold %}
                <div class="col-md-3">
                    <div class = "stock.name">
                        {{ stock.symbol }}
                    </div>
                    <img src="{% static 'Images/stock.svg'%}">
                    <div class = "sentiment_card">No. of Mentions: {{ stock.trend}}</div>
                    <p> <img src="{% static 'Images/dollar.svg'%}">
                        {{ stock.value }}

                    </p>
                
                </div>
                
                {% endfor %}
                
           </div>
       </div>               

    </div>
       
    </body>

{% endblock %}

StockEye/StockEye/app/templates/app/watchlists.html
{% extends "app/layout.html" %}

{% load static %}
{% block content %}

<body>
    
    <h3>My Watchlists</h3>
    {% if user.is_authenticated %}
        <h4>{{ user.username }}'s Current Watchlists</h4>
    {% endif %}

    <!-- Container (Watchlist Section) -->
    <div class="container">

        {% if data %}
            <a href="{% url 'manage_watchlists' %}" class="btn-custom" style="align-content: right;">Manage Watchlists</a>
            <br>
            <br>
        {% else %}
            <a href="{% url 'create_watchlist' %}">Create a new Watchlist</a>
        {% endif %}
   
        
        

        <div  class = "row3">
            {% for watchlist, stocklist in data %}
            </div>
            <div class="row3">
            <div style="clear:both; margin-bottom:20px"></div>
            
            <div class="col-md-3 ">
            
                {% if watchlist.watchList_name %}
                
                    <td style="text-align: center;">{{ watchlist.watchList_name }}</a></td>
                {% else %}
                
                    <td style="text-align: center; ">Watchlist {{ watchlist.watchList_id }}</a></td>
                {% endif %}
            </div>

       
       
            {% for stock in stocklist  %}
                 
            <div class="col-md-3" style="text-align: center;">

                <div class = "stock.name">{{ stock.symbol }}</div>
                    <img src="{% static 'Images/stock.svg'%}">
                    <br>
                <div class = "positive_card"style="text-align:center;">{{ stock.positiveSentimentCount}}</div>
                
                <div class = "negative_card">{{stock.negativeSentimentCount}}</div>
                    
                    <p> <img src="{% static 'Images/dollar.svg'%}">{{ stock.value }} </p>
            
                </div>
                
                {% endfor %}
            
            {% endfor %}
            
        </div>
    </div>

    </div>               



</body>

{% endblock %}